[2023-05-01 00:23:46,867] ERROR log_exception() L1449 Exception on /usuario [GET] - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/alysson/Documentos/full_stack_basic_application_api/application_api/app.py", line 78, in get_usuario
    usuario_id = query.id
AttributeError: 'UsuarioBuscaSchema' object has no attribute 'id'
[2023-05-01 00:23:46,868] INFO _log() L224  127.0.0.1 - - [01/May/2023 00:23:46] "[35m[1mGET /usuario?login=joao01 HTTP/1.1[0m" 500 - - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-05-01 00:23:56,135] ERROR log_exception() L1449 Exception on /usuarios [GET] - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/alysson/Documentos/full_stack_basic_application_api/application_api/app.py", line 71, in get_usuarios
    return apresenta_usuarios(usuarios), 200
  File "/home/alysson/Documentos/full_stack_basic_application_api/application_api/schemas/usuario.py", line 26, in apresenta_usuarios
    "login": usuarios.login,
AttributeError: 'list' object has no attribute 'login'
[2023-05-01 00:23:56,136] INFO _log() L224  127.0.0.1 - - [01/May/2023 00:23:56] "[35m[1mGET /usuarios HTTP/1.1[0m" 500 - - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-05-01 00:25:20,791] WARNING add_comentario() L127  Erro ao adicionar coment√°rio do usu√°rio 'alygon', Usu√°rio n√£o encontrado na base! - call_trace=/home/alysson/Documentos/full_stack_basic_application_api/application_api/app.py L127 
[2023-05-01 00:25:20,791] INFO _log() L224  127.0.0.1 - - [01/May/2023 00:25:20] "[33mPOST /cometario HTTP/1.1[0m" 404 - - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-05-01 00:25:31,686] INFO _log() L224  127.0.0.1 - - [01/May/2023 00:25:31] "POST /cometario HTTP/1.1" 200 - - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-05-01 00:30:34,993] INFO _log() L224   * Detected change in '/home/alysson/Documentos/full_stack_basic_application_api/application_api/schemas/usuario.py', reloading - call_trace=/home/alysson/Documentos/desenvolvimento-full-stack/desenvolvimento-full-stack-basico/aula-3/meu_app_api/env/lib/python3.10/site-packages/werkzeug/_internal.py L224 
